src/refactofing/config/routes.rb
CookBook::Application.routes.draw do
  get "logs/index"
  get "logs/show"
  get "logs/detail"

  resources :password_resets
  resources :user_sessions
  resources :articles
  resources :ingredience_categories
  resources :recipe_categories
  resources :comments

  resources :users do
    member do
      get :activate
      get :recipes
      get :articles
      get :block
      get :unblock
      put :change_password
    end
    
    collection do
      get "reset_password"
    end
  end

  resources :recipes do
    member do
      get "add_ingredience"
      get "remove_ingredience"
      get "add_category"
      get "remove_category"
      get "add_connected_article"
      get "remove_connected_article"
      get "add_subrecipe"
      get "remove_subrecipe"
    end

    collection do
      get "fridge"
      get "newest"
    end
  end
  
  resources :ingrediences do
    collection do
      get "new_request"
    end
  end

  get "help/index"

  get "home/index"
  get "home/search"
  get "home/success"
  get "home/error"
  get "index/home"

  get "user_sessions/create"
  get "user_sessions/destroy"

  get "marks/create"
  get "marks/index"
  get "marks/destroy"

  match 'login' => 'user_sessions#create', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'my_profile' => 'users#show'
  match 'my_recipes' => 'users#recipes'
  match 'my_articles' => 'users#articles'

  match 'fridge' => 'recipes#fridge'
  match 'filter' => 'recipes#filter'
  match 'search' => 'home#search'
  
  match 'logs' => 'logs#index'

  match 'marks' => 'marks#index'

  root :to => 'home#index'

end

src/refactofing/app/models/recipe.rb
# coding:utf-8

class Recipe < ActiveRecord::Base
  belongs_to :user

  has_many :comments
  has_many :marks
  has_many :ingredienceRecipeConnectors
  has_many :ingrediences, :through => :ingredienceRecipeConnectors

  has_and_belongs_to_many :recipeCategories
  has_and_belongs_to_many :articles

  has_many :subrecipes,
    :foreign_key => 'recipe_id', :class_name => 'RecipeRecipeConnector'

  mount_uploader :image, RecipeImageUploader

  attr_accessible :name, :annotation, :content, :level, :estimated_time, :created_at, :image, :image_cache, :recipeCategories, :articles, :user, :user_id

  validates :name,
    :length => { :minimum => 3, :maximum => 50, :message => VALIDATION_ERROR_MESSAGE["recipe"]["name"] }

  validates :annotation,
    :length => { :minimum => 50, :maximum => 255, :message => VALIDATION_ERROR_MESSAGE["recipe"]["annotation"] },
    :allow_blank => true,
    :allow_nil => true

  validates :content,
    :length => { :minimum => 100, :message => VALIDATION_ERROR_MESSAGE["recipe"]["content"] }

  validates :level,
    :numericality => { :only_integer => true, :greater_than_or_equal_to => 0, :less_than  => LEVEL_TEXT.length, :message => VALIDATION_ERROR_MESSAGE["recipe"]["level"] }

  validates :estimated_time,
    :numericality => { :only_integer => true, :greater_than => 0, :message => VALIDATION_ERROR_MESSAGE["recipe"]["user_id"]}

  validates :user_id,
    :presence => { :message => VALIDATION_ERROR_MESSAGE["recipe"]["user_id"] },
    :numericality => { :only_integer => true, :greater_than => 0, :message => VALIDATION_ERROR_MESSAGE["recipe"]["user_id"] }
  validates :user, :associated => { :message => VALIDATION_ERROR_MESSAGE["recipe"]["user_id"] }

  #validates :image
end

src/refactofing/app/controllers/recipes_controller.rb
# coding:utf-8

require 'cgi'
include RecipesHelper

class RecipesController < ApplicationController
  before_filter :user_rights_filter

  def show
    @recipe = Recipe.find(params[:id])

    if current_user
      @my_mark = @recipe.marks.where(:user_id => current_user.id).first
    end

    # seznam komentaru pto recept
    @comments = Comment.where(:recipe_id => @recipe.id)

    # entita na pridani noveho komentare
    @comment = Comment.new
    @comment.user = current_user
    @comment.recipe = @recipe

    # entity na propojeni
    @new_connected_article = RecipeRecipeConnector.new
    @new_connected_article.recipe_id = @recipe.id
    @new_subrecipe = RecipeRecipeConnector.new
    @new_subrecipe.recipe_id = @recipe.id
  end

  def new
    #nastaveni textaci
    @title = "Nový recept"
    @submit_title = "Vytvořit recept"

    @recipe = Recipe.new
    @categories = RecipeCategory.order(:name).all
  end

  def create
    @recipe = Recipe.new(params[:recipe])
    @recipe.user = current_user

    if @recipe.save
      redirect_to @recipe, notice: 'Recept byl úspěšně vytvořen.'
    else
      @errors = @recipe.errors
      render action: "new"
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update_attributes(params[:recipe])
      redirect_to @recipe, notice: 'Recept byl úspěšně upraven.'
    else
      @errors = @recipe.errors
      render action: "edit"
    end
  end

  def edit
    #nastaveni textaci
    @title = "Editace receptu"
    @submit_title = "Upravit recept"

    @recipe = Recipe.find(params[:id])
    @categories = RecipeCategory.order(:name).all
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to "/my_recipes"
  end

  def add_ingredience
    @recipe = Recipe.find(params[:id])
    params[:quantity] = params[:quantity].gsub ",", "."

    if params[:importance] && params[:quantity] && params[:quantity].to_f > 0 && params[:ingredience]
      if @recipe.ingrediences.where(:id => params[:ingredience]).length == 0
        @new_item = IngredienceRecipeConnector.new
        @new_item.importance = params[:importance].to_i
        @new_item.quantity = params[:quantity].to_f
        @new_item.recipe = @recipe
        @new_item.ingredience_id = params[:ingredience]
        @new_item.save
      else
        @item = @recipe.ingredienceRecipeConnectors.where(:ingredience_id => params[:ingredience]).first
        @item.quantity += params[:quantity].to_f
        @item.importance = params[:importance].to_i
        @item.save
      end
    end

    respond_to do |format|
      format.html { redirect_to @recipe }
      format.json {
        render json: @recipe.ingrediences
      }
    end
  end

  def remove_ingredience
    @recipe = Recipe.find(params[:id])

    if params[:connector_id]
      @to_remove = IngredienceRecipeConnector.find(params[:connector_id])
      @to_remove.destroy
    end

    respond_to do |format|
      format.html { redirect_to @recipe }
      format.json {
        render json: @recipe.ingrediences
      }
    end
  end

  def add_category
    @recipe = Recipe.find(params[:id])

    if params[:category] && @recipe.recipeCategories.where(:id => params[:category]).length == 0
      @recipe.recipeCategories << RecipeCategory.find(params[:category])
      @recipe.save
    end

    respond_to do |format|
      format.html { redirect_to @recipe }
      format.json {
        render json: @recipe.recipeCategories
      }
    end
  end

  def remove_category
    @recipe = Recipe.find(params[:id])

    if params[:category]
      @recipe.recipeCategories.delete(RecipeCategory.find(params[:category]))
    end

    respond_to do |format|
      format.html { redirect_to @recipe }
      format.json {
        render json: @recipe.recipeCategories
      }
    end
  end

  def add_subrecipe
    @recipe = Recipe.find(params[:id])

    if params[:subrecipe]
      @tmp = params[:subrecipe].split(/http.?\:\/\/[^\/]+\/recipes?\//)
      if @tmp.length == 2
        @msg = @tmp
        @id = @tmp[1].to_i
        if @id && @recipe.subrecipes.where(:id => @id).length == 0
          @new_item = RecipeRecipeConnector.new
          @new_item.recipe_id = params[:id]
          @new_item.subrecipe_id = @id
          @new_item.save
        end
      end
    end

    respond_to do |format|
      format.html { redirect_to @recipe }
      format.json {
        render json: @recipe.subrecipes
      }
    end
  end

  def remove_subrecipe
    @recipe = Recipe.find(params[:id])

    if params[:subrecipe]
      RecipeRecipeConnector.where(:recipe_id => params[:id]).where(:subrecipe_id => params[:subrecipe]).all? { |e| e.delete }
    end

    respond_to do |format|
      format.html { redirect_to @recipe }
      format.json {
        render json: @recipe.subrecipes
      }
    end
  end

  def add_connected_article
    @recipe = Recipe.find(params[:id])

    if params[:article]
      @tmp = params[:article].split(/http.?\:\/\/[^\/]+\/articles?\//)
      if @tmp.length == 2
        @msg = @tmp
        @id = @tmp[1].to_i
        if @id && @recipe.articles.where(:id => @id).length == 0
          @recipe.articles << Article.find(@id)
        end
      end
    end

    respond_to do |format|
      format.html { redirect_to @recipe }
      format.json {
        render json: @recipe.articles
      }
    end
  end

  def remove_connected_article
    @recipe = Recipe.find(params[:id])

    if params[:article]
      @recipe.articles.delete(Article.find(params[:article]))
    end

    respond_to do |format|
      format.html { redirect_to @recipe }
      format.json {
        render json: @recipe.articles
      }
    end
  end

  def fridge
    @ingrediences = Hash.new
    @ingrediences[:accepted] = Ingredience.where(:activation_state => 1).order(:name).all
    @ingrediences[:not_accepted] = Ingredience.where(:activation_state => 0).order(:name).all

    @fridge_result = get_recipes_by_fridge(params)
    @recipes = @fridge_result ? @fridge_result[:recipes] : []
    @badges = @fridge_result ? @fridge_result[:badges] : []
  end

  def filter
    @recipes = get_recipes_by_filter(params[:filter])
  end

  def newest
    @results_title = "Nejnovější recepty"
    @recipes = Recipe.get_recipes_sorted_by_date(params[:count] == nil ? 10 : params[:count].to_i)
  end
end

src/refactofing/app/helpers/recipes_helper.rb
# coding:utf-8

module RecipesHelper
  def get_mark(recipe)
    sum = 0
    count = 0
    recipe.marks.each do |mark|
      sum += mark.value;
      count += 1;
    end
    return count > 0 ? (sum/count).round(1) : nil;
  end

  def get_mark_str(recipe)
    mark = get_mark(recipe);
    return mark != nil ? mark.to_s : "žádné";
  end

  def get_recipe_koef_for_fridge(recipe, p)
    koef = 0.0;
    sum = 0.0;
    # pokud nemam u receptu zadne ingredience, vrati se mi s nejnizsim moznym
    # vysledkem tak, aby byl zahrnut do vysledku, ale az na posledni pozici
    if recipe.ingredienceRecipeConnectors.length == 0
      return MIN_KOEF_FOR_FRIDGE_RESULT
    end
    # pokud ingredience mam, pocitam
    for recipe_ingredience in recipe.ingredienceRecipeConnectors
      sum += recipe_ingredience.importance
      for ingredience in p
        if (ingredience[:id] == recipe_ingredience.ingredience_id)
          koef += [1, ingredience[:quantity] ? (ingredience[:quantity]/recipe_ingredience.quantity) : 1].min * recipe_ingredience.importance
        end
      end
    end
    return koef / sum;
  end

  #############
  # DB FILTRY #
  #############

  def get_recipes_by_keyphrase(phrase)

  end

  # pokud je count null, vraci vsechny, jinak omezeny pocet
  def get_recipes_sorted_by_date(count)
    return count == nil ?
        Recipe.order("created_at DESC").all :
        Recipe.order("created_at DESC").limit(count).all
  end

  # date je string pro porovnavani pomoci like
  def get_recipes_by_date(date, count)
    return count == nil ?
        Recipe.where("created_at LIKE "+date).all :
        Recipe.where("created_at LIKE "+date).limit(count).all
  end

  def get_recipes_sorted_by_random(count)
    return count == nil ?
        Recipe.order("random()").all :
        Recipe.order("random()").limit(count).all

    return @ret
  end

  def get_recipes_sorted_by_mark(count)
    @ret = Recipe.all(
      :select => "
        recipes.*,
        AVG(marks.value) as avg_value,
        MIN(marks.value) as min_value,
        MAX(marks.value) as max_value",
      :joins => :marks,
      :group => 'recipes.id'
    )

    return count == nil ? @ret : @ret.first(count)
  end

  def get_recipes_by_filter(filter)
    if (filter == nil)
      return Recipe.order(:name).all
    end

    ret = Recipe.order(:name);

    if (filter[:text] && filter[:text] != "")
      tmp = "(name LIKE :filter)"
      if filter[:text_type] == "1"
        tmp += "OR(annotation LIKE :filter)"
        tmp += "OR(content LIKE :filter)"
      end
      ret = ret.where(tmp, :filter => '%' + filter[:text] + '%')
    end

    if (filter[:level] && filter[:level] != "")
      ret = ret.where("level = " + filter[:level])
    end

    if (filter[:time_min] && filter[:time_min] != "")
      ret = ret.where("estimated_time >= " + filter[:time_min])
    end

    if (filter[:time_max] && filter[:time_max] != "")
      ret = ret.where("estimated_time <= " + filter[:time_max])
    end

    return ret.all
  end

  def get_recipes_by_fridge(p)
    if (p == nil || p[:ingrediences] == nil || !(p[:ingrediences].length > 0))
      return nil
    end

    recipes = Recipe.all;
    parsedP = Array.new
    inStr = "" # string pro WHERE ? IN (.....)


    if p[:ingrediences]
      for str in p[:ingrediences].each
        tmp = str.split("|");
        parsedP << { :id => tmp[0].to_i, :quantity => tmp[1] ? tmp[1].to_f : nil }
        if (inStr != "")
          inStr += ","
        end
        inStr += tmp[0] # tohle je string, tak abych to nemusel znova prevedet, neberu z parsedP
      end
    end

    # TODO - yatim neimplementuju dostupnost ingredienci
    #ingrediences = Ingredience.where("id IN (" + inStr + ")").all
    #concat("id IN (" + inStr + ")")

    # pocitani koeficienu
    list = Array.new
    for recipe in recipes
      koef = get_recipe_koef_for_fridge(recipe, parsedP)
      if (koef >= MIN_KOEF_FOR_FRIDGE_RESULT)
        list << { :recipe => recipe, :koef => koef}
      end
    end

    #razeni
    ret = Array.new
    badges = Hash.new
    while list.length > 0
      max_item = nil
      for item in list
        if max_item == nil || item[:koef] > max_item[:koef]
          max_item = item
        end
      end
      badges[max_item[:recipe].id] = Hash.new
      if max_item[:koef] > 0.9
        badges[max_item[:recipe].id]['class'] = "badge-success"
        badges[max_item[:recipe].id]['title'] = "doporučujeme"
      else if max_item[:koef] > 0.8
        badges[max_item[:recipe].id]['class'] = nil
        badges[max_item[:recipe].id]['title'] = "možná uvaříte"
      else if max_item[:koef] > 0.6
        badges[max_item[:recipe].id]['class'] = "badge-waring"
        badges[max_item[:recipe].id]['title'] = "s drobným nákupem"
      else
        badges[max_item[:recipe].id]['class'] = "badge-important"
        badges[max_item[:recipe].id]['title'] = "něco vám chybí"
      end end end
      ret << max_item[:recipe]
      list.delete(max_item)
    end

    return { :recipes => ret, :badges => badges }
  end
end

src/refactofing/app/views/recipes/_form.html.erb
<script type="text/javascript" src="<%= asset_path "pages/recipes_form.js" %>"></script>

<div class="span8 offset2">
  <div class="well">
    <h2><%= @title %></h2>
    <%= form_for(@recipe, :html => { :onsubmit => "return Validator.validate({ group: \"recipe_form\", showMessage: false })" }) do |f| %>
      <%= render "layouts/errors" %>

      <h4>Název</h4>
      <div class="row-fluid spacer">
        <div class="span4">
          <%= f.text_field :name, :placeholder => "Název receptu" %>
        </div>
        <div class="span4">
          <p>
            Obrázek:
            <%= f.hidden_field :image_cache %>
            <%= f.file_field :image %>
          </p>
        </div>
      </div>

      <hr />

      <h4>Popis</h4>
      <div class="row-fluid spacer">
        <label class="spacer">Stručný popis receptu</label>
        <%= f.text_area :annotation, :class => "input-block-level", :rows => "3" %>

        <label class="spacer">Popis receptu</label>
        <%= f.text_area :content, :class => "input-block-level", :rows => "10" %>
      </div>

      <hr />

      <h4>Doplňující informace</h4>

      <label>Složitost přípravy</label>
      <%= f.select :level, options_for_select(get_recipe_level_options, @recipe.level.to_s) %>

      <label>Odhadovaný čas přípravy (minuty)</label>
      <%= f.number_field :estimated_time %>
      
      <p></p>

      <%= f.submit @submit_title, :class => "btn" %>
    <% end %>
  </div>
</div>

src/refactofing/app/views/recipes/_list.html.erb
<div class="well recipes-list">
  <h2><%= @results_title ? @results_title : "Výsledky hledání" %></h2>
  <% if @recipes != nil %>
    <% @recipes.each do |recipe| %>
      <div class="spacer well active" onclick="window.location = '<%= recipe_path(recipe.id) %>'">
        <div class="pull-left">
          <%= get_thumb_icon(recipe) %>
        </div>
        <div>
          <h5>
            <%= recipe.name %>
            <% if @badges && @badges[recipe.id] %>
              <span class="badge <%= @badges[recipe.id]['class'] %>"><%= @badges[recipe.id]['title'] %></span>
            <% end %>-
            <%= users_filter("show", {:id => recipe.user.id.to_s }) ? link_to(recipe.user.username, user_path(recipe.user)) : recipe.user.username %> -
            <%= recipe.created_at %>
          </h5>
          <p><%= recipe.annotation %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

src/refactofing/app/views/recipes/edit.html.erb
<%= render "form" %>

src/refactofing/app/views/recipes/filter.html.erb
<div class="span2"></div>
<div class="span8">
  <%= render 'list' %>
</div>

src/refactofing/app/views/recipes/new.html.erb
<%= render "form" %>

src/refactofing/app/views/recipes/newest.html.erb
<div class="span2"></div>
<div class="span8">
  <%= render 'list' %>
</div>

src/refactofing/app/views/recipes/show.html.erb
<script type="text/javascript" src="<%= asset_path "pages/recipes_show.js" %>"></script>

<input type="hidden" id="recipe_id" value="<%= @recipe.id %>" />
<div class="span2">
  <div class="well">
    <h4>Odkazy na podpostupy</h4>
    <ul id="subrecipes" class="unstyled">
      <% @recipe.subrecipes.each do |subrecipe| %>
        <span>
          <%= link_to subrecipe.subrecipe.name, recipe_path(subrecipe.subrecipe) %>
          <% if recipes_filter("edit", nil, @recipe) %>
            <form action="/recipes/<%= @recipe.id.to_s %>/remove_subrecipe" method="GET">
              <input type="hidden" name="subrecipe" value="<%= subrecipe.subrecipe.id.to_s %>" />
              <input type="submit" value="X" class="btn" />
            </form>
          <% end %>
          <br />
        </span>
      <% end %>
      <span id="recipes_empty" class="<%= @recipe.subrecipes.length == 0 ? nil : "hidden" %>">
        Žádné
        <br />
      </span>
    </ul>
    <span id="subrecipe-form-errors"><!-- error hlasky pro podrecept --></span>
    <% if recipes_filter("edit", nil, @recipe) %>
      <form action="/recipes/<%= @recipe.id.to_s %>/add_subrecipe"
            method="get"
            onsubmit="
              return Validator.validate({
                group: 'subrecipe_form',
                errorsElementId: 'subrecipe-form-errors'
              })">
        <input name="subrecipe" id="new_subrecipe_url" type="text" />
        <input type="submit" class="btn" value="Přidat podpostup" />
      </form>
    <% end %>
    <legend></legend>
    <h4>Zajímavé články k receptu</h4>
    <ul id="articles" class="unstyled">
      <% @recipe.articles.each do |article| %>
        <span>
          <%= link_to article.title, article_path(article) %>
          <% if recipes_filter("edit", nil, @recipe) %>
            <form action="/recipes/<%= @recipe.id.to_s %>/remove_connected_article" method="GET">
              <input type="hidden" name="article" value="<%= article.id.to_s %>" />
              <input type="submit" value="X" class="btn" />
            </form>
          <% end %>
          <br />
        </span>
      <% end %>
      <% if @recipe.articles.length == 0 %>
        <span>Žádné<br /></span>
      <% end %>
    </ul>
    <span id="article-form-errors"><!-- error hlasky pro clanek --></span>
    <% if recipes_filter("edit", nil, @recipe) %>
      <form action="/recipes/<%= @recipe.id.to_s %>/add_connected_article"
            method="get"
            onsubmit="
              return Validator.validate({
                group: 'article_form',
                errorsElementId: 'article-form-errors'
              })">
        <input name="article" id="new_article_url" type="text" />
        <input type="submit" class="btn" value="Přidat článek" />
      </form>
    <% end %>
  </div>

  <% if recipes_filter("edit", nil, @recipe) %>
    <div class="well">
      <span id="ingredience-request-form-errors"><!-- error hlasky pro clanek --></span>
      <legend>Podat žádost na ingredienci</legend>
      <input id="ingredience_request_name" type="text" placeholder="Název" />
      <input id="ingredience_request_units" type="text" placeholder="Jednotky" />
      <label>Stručný popis</label>
      <textarea id="ingredience_request_annotation" cols="" rows="3" class="input-block-level"></textarea>
      <label>Popis</label>
      <textarea id="ingredience_request_content" cols="" rows="5" class="input-block-level"></textarea>
      <button class="btn" onclick="IngredienceRequest.submit()">Podat žádost</button>
    </div>
  <% end %>
</div>

<div class="span8">
  <div class="well">
    <h2><%= @recipe.name %></h2>
    <div class="row-fluid spacer">
      <% if @recipe.image != nil %>
        <div class="span6">
          <%= get_icon(@recipe) %>
        </div>
      <% end %>
      <div class="span6">
        <dl class="dl-horizontal">
          <% @recipe.ingredienceRecipeConnectors.each do |ingredienceConn| %>
            <dt>
              <%= ingrediences_filter("show", nil, ingredienceConn.ingredience) ?
                link_to(ingredienceConn.ingredience.name, ingredience_path(ingredienceConn.ingredience)) : ingredienceConn.ingredience.name %>
            </dt>
            <dd>
              <%= ingredienceConn.quantity %>
              <%= ingredienceConn.ingredience.units %>
              <% if recipes_filter("edit", nil, @recipe) %>
                (důležitost: <%= ingredienceConn.importance %>)
              <% end %>
              <% if recipes_filter("remove_ingredience", nil, @recipe) %>
                <%= link_to "(smazat)", "/recipes/"+@recipe.id.to_s+"/remove_ingredience?connector_id="+ingredienceConn.id.to_s %>
              <% end %>
            </dd>
          <% end %>
        </dl>
      </div>
    </div>

    <% if recipes_filter("edit", nil, @recipe) %>
      <legend class="spacer"></legend>

      <div class="spacer">
        <% if recipes_filter("add_ingredience", nil, @recipe) %>
          <div>
            <span id="add-ingredience-form-errors"><!-- error hlasky pro clanek --></span>
            <form action="/recipes/<%= @recipe.id %>/add_ingredience"
                  method="GET"
                  onsubmit="
                    return Validator.validate({
                      group: 'add_ingredience_form',
                      errorsElementId: 'add-ingredience-form-errors'
                    })">
              <select name="ingredience" id="new_ingredience_list">
                <optgroup label="Schválené" id="new_ingredience_list_accepted"></optgroup>
                <optgroup label="Neschválené" id="new_ingredience_list_pending"></optgroup>
              </select>
              <input type="text" name="quantity" id="new_ingredience_quantity" class="input-small" placeholder="množství" />
              <input type="text" name="importance" id="new_ingredience_importance" class="input-small" placeholder="důležitost" />
              <input type="submit" value="Přidat ingredienci" class="btn" />
            </form>
          </div>
        <% end %>
        <% if recipes_filter("add_category", nil, @recipe) %>
          <div>
            <span id="add-category-form-errors"><!-- error hlasky pro clanek --></span>
            <form action="/recipes/<%= @recipe.id %>/add_category"
                  method="GET"
                  onsubmit="
                    return Validator.validate({
                      group: 'add_category_form',
                      errorsElementId: 'add-category-form-errors'
                    })">
              <select name="category" id="new_category_list">
                <% for category in RecipeCategory.order(:name).all %>
                  <option value="<%= category.id %>"><%= category.name %></option>
                <% end %>
              </select>
              <input type="submit" value="Přidat kategorii" class="btn" />
            </form>
          </div>
        <% end %>
      </div>

      <legend class="spacer"></legend>
    <% end %>

    <div class="spacer">
      <p><b>Složitost:</b>
        <span class="badge <%= LEVEL_CLASS[@recipe.level] %>"><%= LEVEL_TEXT[@recipe.level] %></span>
      </p>
      <p><b>Odhadovaný čas:</b> <%= @recipe.estimated_time %> min</p>
      <p>
        <b>Kategorie:</b>
        <% for category in @recipe.recipeCategories %>
          <%= category.name + (category != @recipe.recipeCategories.last ? ", " : "") %>
          <% if recipes_filter("remove_category", nil, @recipe) %>
            <%= link_to "(smazat)", "/recipes/"+@recipe.id.to_s+"/remove_category?category="+category.id.to_s %>
          <% end %>
        <% end %>
      </p>
    </div>

    <legend class="spacer"></legend>

    <div class="spacer">
      <p><%= @recipe.annotation %></p>
      <p><%= simple_format @recipe.content %></p>
    </div>

    <legend class="spacer"></legend>

    <div class="spacer">
      <% if marks_filter("show", nil, nil) %>
        <h5>
          Hodnocení: <span id="recipe_mark"><%= get_mark_str @recipe %></span>
          <span id="recipe_my_mark_wrapper" class="<%= @my_mark ? nil : "hidden" %>">
            (moje hodnocení:
            <span id="recipe_my_mark">
              <%= @my_mark ? @my_mark.value : nil %>
            </span>
            )
          </span>
        </h5>
      <% end %>
      <% if marks_filter("create", nil, nil) %>
        <div id="star">
          <div id="star1" class="btn btn-small" onclick="RecipeMark.submit(1)"><i class="icon-star"></i></div>
          <div id="star2" class="btn btn-small" onclick="RecipeMark.submit(2)"><i class="icon-star"></i></div>
          <div id="star3" class="btn btn-small" onclick="RecipeMark.submit(3)"><i class="icon-star"></i></div>
          <div id="star4" class="btn btn-small" onclick="RecipeMark.submit(4)"><i class="icon-star"></i></div>
          <div id="star5" class="btn btn-small" onclick="RecipeMark.submit(5)"><i class="icon-star"></i></div>
        </div>
      <% end %>

      <label></label>

      <%#= marks_filter("delete", nil, @my_mark) ? button_to("Smazat moje hodnocení", "/marks/destroy?id="+@my_mark.id.to_s, { :method => :get, :id => "recipe_delete_mark", :class => "btn" + (@my_mark ? "" : " hidden")}) : nil %>
      <%= recipes_filter("edit", nil, @recipe) ? button_to("Upravit recept", { :controller => "recipes", :action => "edit", :id => @recipe.id}, { :method => :get, :class => "btn"}) : nil %>
    </div>

    <legend class="spacer"></legend>

    <%= render "comments/list" %>
    <%= render "comments/form" %>
  </div>
</div>