src/refactofing/config/routes.rb
CookBook::Application.routes.draw do
  get "logs/index"
  get "logs/show"
  get "logs/detail"

  resources :password_resets
  resources :user_sessions
  resources :articles
  resources :ingredience_categories
  resources :recipe_categories
  resources :comments

  resources :users do
    member do
      get :activate
      get :recipes
      get :articles
      get :block
      get :unblock
      put :change_password
    end
    
    collection do
      get "reset_password"
    end
  end

  resources :recipes do
    member do
      get "add_ingredience"
      get "remove_ingredience"
      get "add_category"
      get "remove_category"
      get "add_connected_article"
      get "remove_connected_article"
      get "add_subrecipe"
      get "remove_subrecipe"
    end

    collection do
      get "fridge"
      get "newest"
    end
  end
  
  resources :ingrediences do
    collection do
      get "new_request"
    end
  end

  get "help/index"

  get "home/index"
  get "home/search"
  get "home/success"
  get "home/error"
  get "index/home"

  get "user_sessions/create"
  get "user_sessions/destroy"

  get "marks/create"
  get "marks/index"
  get "marks/destroy"

  match 'login' => 'user_sessions#create', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'my_profile' => 'users#show'
  match 'my_recipes' => 'users#recipes'
  match 'my_articles' => 'users#articles'

  match 'fridge' => 'recipes#fridge'
  match 'filter' => 'recipes#filter'
  match 'search' => 'home#search'
  
  match 'logs' => 'logs#index'

  match 'marks' => 'marks#index'

  root :to => 'home#index'

end

src/refactofing/app/models/user.rb
# coding:utf-8

class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :recipes
  has_many :articles
  has_many :ingrediences
  has_many :comments
  has_many :marks
  has_many :ingredienceCategories
  has_many :recipeCategories

  attr_accessible :username, :email, :password, :password_confirmation, :first_name, :second_name, :age, :note, :active, :self_ruleset, :others_ruleset, :activation_state, :activation_token, :activation_token_expires_at

  validates :username,
    :format => { :with => /^[a-zA-Z0-9\-\.\_]{3,30}$/, :message => VALIDATION_ERROR_MESSAGE["user"]["username"]["format"] },
    :uniqueness => { :case_sensitive => false, :message => VALIDATION_ERROR_MESSAGE["user"]["username"]["uniqueness"] }

  validates :email,
    :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => VALIDATION_ERROR_MESSAGE["user"]["email"]["format"] },
    :uniqueness => { :case_sensitive => false, :message => VALIDATION_ERROR_MESSAGE["user"]["email"]["uniqueness"] }

  validates :password,
    :length => { :minimum => 3, :maximum => 255, :message => VALIDATION_ERROR_MESSAGE["user"]["password"]["length"] },
    :confirmation => { :message => VALIDATION_ERROR_MESSAGE["user"]["password"]["confirmation"] },
    :allow_blank => false,
    :allow_nil => false,
  :if => :password

  validates :first_name,
    :format => { :with => /^(|.{2,})$/, :message => VALIDATION_ERROR_MESSAGE["user"]["first_name"] },
    :allow_nil => true,
    :allow_blank => true

  validates :second_name,
    :format => { :with => /^(|.{2,})$/, :message => VALIDATION_ERROR_MESSAGE["user"]["second_name"] },
    :allow_nil => true,
    :allow_blank => true

  validates :age, 
    :numericality => { :only_integer => true, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 100, :message => VALIDATION_ERROR_MESSAGE["user"]["age"] },
    :allow_nil => true,
    :allow_blank => true

  #validates :note

  #validates :active

  validates :self_ruleset,
    :numericality => { :only_integer => true, :message => VALIDATION_ERROR_MESSAGE["user"]["self_ruleset"] }

  validates :others_ruleset,
    :numericality => { :only_integer => true, :message => VALIDATION_ERROR_MESSAGE["user"]["others_ruleset"] }

#  validates :crypted_password,
#    :length => { :minimum => 1, :message => "špatné heslo" },
#    :allow_nil => false,
#    :allow_blank => false

  #validates :activation_state

  #validates :activation_token

  #validates :activation_token_expires_at
end

src/refactofing/app/controllers/users_controller.rb
# coding:utf-8

class UsersController < ApplicationController
  before_filter :user_rights_filter
  
  # GET /users
  # GET /users.json
  def index
    filter = get_filter("username")
    if (filter != nil)
      @users = User.where("username like ?", "%" + filter +"%").order(:username).all
    else
      @users = User.order(:username).all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id] ? params[:id] : current_user.id)

    @users = User.all
    @links_title = "Další uživatelé"
    @links = []
    for user in @users
      if (user != @user)
        @links.push([user.username, user_path(user)])
      end
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id] ? params[:id] : current_user.id)
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.self_ruleset = RULES_SELF_DEFAULT
    @user.others_ruleset = RULES_OTHERS_DEFAULT

    if @user.save
      UserMailer.activation_needed_email(@user).deliver
      redirect_to  "/home/success", notice: 'Na email, zadaný při registraci byl zaslán kontrolní mail. Účet aktivujete kliknutím na odkaz uvnitř mailu.'
    else
      @errors = @user.errors
      render action: "new"
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'Uživatel byl úspěšně upraven.'
    else
      @errors = @user.errors
      render action: "edit"
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      UserMailer.activation_success_email(@user).deliver
      # presmeruju na seznam uzivatelu, pokud neni zdrojem aktivace email
      redirect_to(params[:src] == "email" ? "/home/success" : "/users", :notice => 'Uživatel byl úspěšně aktivován.')
    else
      not_authenticated
    end
  end

  def recipes
    @user = User.find(params[:id] ? params[:id] : current_user.id)
    @recipes = @user.recipes;
    @commented = @user.comments.where("recipe_id IS NOT NULL")
    @marked = @user.marks
    @splitted = Array.new
    @commented.each do |item|
      if !@splitted.include?(item.recipe)
        @splitted << item.recipe
      end
    end
    @marked.each do |item|
      if !@splitted.include?(item.recipe)
        @splitted << item.recipe
      end
    end
  end

  def articles
    @user = User.find(params[:id] ? params[:id] : current_user.id)
    @articles = @user.articles;
    @commented_all = @user.comments.where("article_id IS NOT NULL")
    @commented = Array.new
    @commented_all.each do |item|
      if !@commented.include?(item.article)
        @commented << item.article
      end
    end
  end

  def block
    @user = User.find(params[:id])
    state = NIL;
    if (!is_admin(@user) && !is_current_user(@user))
      @user.active = false
      if !@user.save
        state = "Blokování uživatele selhalo!"
      end
    else
      state = "Nelze blokovat administrátorský účet ani aktuálního uživatele!"
    end

    redirect_to users_path, notice: state
  end

  def unblock
    @user = User.find(params[:id])
    state = NIL;
    # jen pro jistotu. Admin by nemel byt nikdy zablokovany a blokovany uzivatel
    # by se neprihlasil (nebyl by current).
    if (!is_admin(@user) && !is_current_user(@user))
      @user.active = true
      if !@user.save
        state = "Odblokování uživatele selhalo!"
      end
    else
      state = "Nelze odblokovat administrátorský účet ani aktuálního uživatele!"
    end

    redirect_to users_path, notice: state
  end

  def change_password
    @user = User.find(params[:id])
    if (@user && User.authenticate(@user.username, params[:user][:old_password]))
      @user.password_confirmation = params[:user][:password_confirmation]
      # the next line clears the temporary token and updates the password
      if @user.change_password!(params[:user][:password])
        redirect_to(@user, :notice => 'Heslo úspěšně změněno.')
      else
        @user.errors.add(:password, "Heslo se nepodařilo změnit!" )
        @errors = @user.errors
        render :action => "edit"
      end
    else
      @user.errors.add(:old_password, "Staré heslo je chybné!" )
      @errors = @user.errors
      render :action => "edit"
    end
  end

  def reset_password
    # jen renderuju formular
  end
end

src/refactofing/app/helpers/users_helper.rb
# coding:utf-8

module UsersHelper
  def index_get_row_class(user)
    if (is_admin(user))
      return "info"
    end

    return user.active ? "" : "error"
  end

  def get_action_buttons(user)
    ret = Array.new;

    #states
    tmp = get_change_state_button(user);
    if tmp != nil
      ret << tmp
    end

    #edit
    tmp = get_edit_button(user);
    if tmp != nil
      ret << tmp
    end

    #edit
    tmp = get_destroy_button(user);
    if tmp != nil
      ret << tmp
    end

    return ret;
  end

  def get_change_state_button(user)
    if (is_admin(user) || is_current_user(user))
      if users_filter("block", :id => user.id)
        return link_to "Zablokovat", users_path, {:method => "get", :class => "btn"}
      end
    end

    if !is_activated(user)
      if users_filter("activate", :id => user.id)
        return link_to "Aktivovat", { :controller => 'users', :action => 'activate', :id => "#{user.activation_token}", :redirect => "/users"}, {:method => "get", :class => "btn"}
      end
    else
      if user.active
        if users_filter("block", :id => user.id)
          return link_to "Zablokovat", { :controller => 'users', :action => 'block', :id => user.id}, {:method => "get", :class => "btn"}
        end
      else
        if users_filter("unblock", :id => user.id)
          return link_to "Odblokovat", { :controller => 'users', :action => 'unblock', :id => user.id}, {:method => "get", :class => "btn"}
        end
      end
    end

    return nil
  end

  def get_edit_button(user)
    if users_filter("edit", :id => user.id)
      return link_to "Editovat", { :controller => 'users', :action => 'edit', :id => user.id}, {:method => "get", :class => "btn"}
    else
      return nil
    end
  end

  def get_destroy_button(user)
    if users_filter("destroy", :id => user.id)
      return nil; # zatim neni implementovano
#      return link_to "Smazat", { :controller => 'users', :action => 'destroy', :id => user.id}, {:method => "get", :class => "btn" }
    else
      return nil
    end
  end

  def edit_get_rule_checkbox(user, rulevalue, type)
    checked = false;
    if type == 0
      checked = user_has_permission(user, rulevalue, nil)
    end
    if type == 1
      checked = user_has_permission(user, nil, rulevalue)
    end
    if type == 2
      checked = user_has_permission(user, rulevalue, rulevalue)
    end

    return check_box("xxx", nil, {:checked => checked, :onchange => "UserRights.update(this.checked, " + (rulevalue.to_s) +", " + (type.to_s) + ")"})
  end
end

src/refactofing/app/views/users/articles.html.erb
<div class="span8 offset2 well">
  <h2>Moje recepty</h2>
  <div class="row-fluid spacer">
    <div class="span5">
      <legend>Napsané články</legend>
      <ul class="unstyled">
        <% @articles.each do |article| %>
          <li><%= link_to article.title, article_path(article) %> - <%= l article.created_at  %></li>
        <% end %>
      </ul>
      <a class="btn spacer" href="<%= new_article_path %> "><i class="icon-pencil"></i> Napsat nový článek</a>
    </div>

    <div class="span6 pull-right">
      <legend>Komentované články</legend>
      <ul class="unstyled">
        <% for commented in @commented %>
          <li>
            <%= link_to commented.title, commented %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

src/refactofing/app/views/users/edit.html.erb
<script type="text/javascript" src="<%=asset_path "pages/users.js" %>"></script>
<div class="span2"></div>
<div class="span8">
  <div class="well">
    <%= render "layouts/errors" %>
    <h2>Moje údaje</h2>
    <div class="row-fluid spacer">
        <%= form_for(@user) do |f| %>
          <dl class="dl-horizontal">
            <dt>Uživatelské jméno:</dt>
            <dd>
              <%= f.text_field :username, :disabled => true %>
            </dd>
            <dt>E-mail:</dt>
            <dd>
              <%= f.email_field :email, :disabled => true %>
            </dd>
            <dt>Jméno:</dt>
            <dd>
              <%= f.text_field :first_name %>
            </dd>
            <dt>Příjmení:</dt>
            <dd>
              <%= f.text_field :second_name %>
            </dd>
            <dt>Aktivační status</dt>
            <dd>
              <span title="Aktivační status lze měnit pomocí tlačítek v seznamu uživatelů/detailu uživatele.">
                <%= @user.activation_state %> *
              </span>
            </dd>
            <% if has_permission_self_other(is_current_user(@user.id), ROLE["users"]["edit_rights"]) %>
              <dt>Oprávnění (vlastní):</dt>
              <dd>
                <div id="defined_rules_self">
                  <%= edit_get_rule_checkbox(@user, ROLE["users"]["show"], 0) %> uživatel: zobrazit<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["users"]["edit"], 0) %> uživatel: editovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["users"]["edit_rights"], 0) %> uživatel: editovat práva<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["recipes"]["create"], 0) %> recept: vytvářet<br />
                  <input type="checkbox" checked disabled /> recept: zobrazovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["recipes"]["edit"], 0) %> recept: editovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["recipes"]["delete"], 0) %> recept: mazat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["articles"]["create"], 0) %> článek: vytvářet<br />
                  <input type="checkbox" checked disabled /> článek: zobrazovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["articles"]["edit"], 0) %> článek: editovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["articles"]["delete"], 0) %> článek: mazat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["comments"]["create"], 0) %> komentáře: vytvářet<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["comments"]["edit"], 0) %> komentáře: editovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["comments"]["delete"], 0) %> komentáře: mazat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["marks"]["create"], 0) %> hodnocení: vytvářet<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["marks"]["delete"], 0) %> hodnocení: mazat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["ingrediences"]["create_delete"], 0) %> ingredience: vytvářet / mazat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["ingrediences"]["edit"], 0) %> ingredience: editovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["recipeCategories"]["create_delete"], 0) %> kategorie receptu: vytvářet / mazat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["recipeCategories"]["edit"], 0) %> kategorie receptu: editovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["ingredienceCategories"]["create_delete"], 0) %> kategorie ingrediencí: mazat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["ingredienceCategories"]["edit"], 0) %> kategorie ingrediencí: editovat
                </div>
              </dd>
              <dt>Oprávnění (cizí):</dt>
              <dd>
                <div id="defined_rules_other">
                  <%= edit_get_rule_checkbox(@user, ROLE["users"]["show"], 1) %> uživatel: zobrazit<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["users"]["edit"], 1) %> uživatel: editovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["users"]["delete"], 1) %> uživatel: mazat (vyjma admina)<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["users"]["edit_rights"], 1) %> uživatel: editovat práva<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["users"]["block"], 1) %> uživatel: blokovat (vyjma admina)<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["users"]["unblock"], 1) %> uživatel: odblokovávat (vyjma admina)<br />
                  <input type="checkbox" checked disabled /> recept: zobrazovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["recipes"]["edit"], 1) %> recept: editovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["recipes"]["delete"], 1) %> recept: mazat<br />
                  <input type="checkbox" checked disabled /> článek: zobrazovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["articles"]["edit"], 1) %> článek: editovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["articles"]["delete"], 1) %> článek: mazat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["comments"]["edit"], 1) %> komentáře: editovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["comments"]["delete"], 1) %> komentáře: mazat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["marks"]["delete"], 1) %> hodnocení: mazat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["ingrediences"]["create_delete"], 1) %> ingredience: mazat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["ingrediences"]["edit"], 1) %> ingredience: editovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["recipeCategories"]["create_delete"], 1) %> kategorie receptu: mazat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["recipeCategories"]["edit"], 1) %> kategorie receptu: editovat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["ingredienceCategories"]["create_delete"], 1) %> kategorie ingrediencí: mazat<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["ingredienceCategories"]["edit"], 1) %> kategorie ingrediencí: editovat<br />
                </div>
              </dd>
              <dt>Oprávnění (globální):</dt>
              <dd>
                <div id="defined_rules_global">
                  <%= edit_get_rule_checkbox(@user, ROLE["users"]["index"], 2) %> zobrazování seznamu uživatelů<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["marks"]["index"], 2) %> zobrazování seznamu známek<br />
                  <%= edit_get_rule_checkbox(@user, ROLE["marks"]["show"], 2) %> zobrazování známek<br />
                </div>
              </dd>
              <% end %>
            </dl>

          <%= f.hidden_field :self_ruleset, {:id => "self_ruleset"} %>
          <%= f.hidden_field :others_ruleset, {:id => "others_ruleset"} %>
          <%= f.submit "Změnit údaje", :class => "btn pull-right" %>
        <% end %>
      </div>

      <div class="row-fluid spacer">
        <%= form_for(@user, :url => { :action => "change_password" }) do |f| %>
          <dl class="dl-horizontal">
            <dt>Staré heslo:</dt>
            <dd>
              <%= f.password_field :old_password, :value => "" %>
            </dd>
            <dt>Nové heslo: </dt>
            <dd>
              <%= f.password_field :password, :value => "" %>
            </dd>
            <dt>Nové heslo znova: </dt>
            <dd>
              <%= f.password_field :password_confirmation, :value => "" %>
            </dd>
          </dl>
          <%= f.submit "Změnit heslo", :class => "btn pull-right" %>
        <% end %>
      </div>
  </div>
</div>

src/refactofing/app/views/users/index.html.erb
<div class="span8 offset2 well">
  <h2>Správa uživatelů</h2>

  <label class="spacer">Vyhledat uživatele: </label>
  <div class="input-append">
    <form id="users-filter" action="/users">
      <input type="text" name="filter[username]" placeholder="Uživatelské jméno" value="<%= get_filter "username" %>" />
      <button class="btn" type="submit">Vyhledat</button>
    </form>
  </div>

  <table class="table table-hower spacer">
    <thead>
      <tr>
        <th>#</th>
        <th>Uživatelské jméno</th>
        <th>E-mailová adresa</th>
        <th>Příjmení</th>
        <th>Jméno</th>
        <th>Aktivován</th>
        <th>Akce</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr class="<%= index_get_row_class user %>">
          <td><%= user.id %></td>
          <td><%= users_filter("show", :id => user.id) ? link_to(user.username, user_path(user)) : user.username %></td>
          <td><%= user.email %></td>
          <td><%= user.second_name %></td>
          <td><%= user.first_name %></td>
          <td><%= user.activation_state %></td>
          <td class="btn-group">
            <% get_action_buttons(user).each do |button| %>
              <%= button %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

src/refactofing/app/views/users/new.html.erb
<div class="span8 offset2">
  <div class="well">
    <h2>Registrace</h2>

    <%= form_for(@user) do |f| %>
      <%= render "layouts/errors" %>
    
      <div class="row-fluid spacer">
        <div class="span5">
          <legend>Povinné údaje</legend>
          <label>Uživatelské jméno</label>
          <%= f.text_field :username %>
          <label>E-mail adresa</label>
          <%= f.email_field :email %>
          <label>Heslo</label>
          <%= f.password_field :password %>
          <label>Potvr. heslo</label>
          <%= f.password_field :password_confirmation %>
        </div>
        <div class="span5 offset2">
          <legend>Další údaje</legend>
          <label>Jméno</label>
          <%= f.text_field :first_name %>
          <label>Příjmení</label>
          <%= f.text_field :second_name %>
          <label>Věk</label>
          <%= f.number_field :age, :min => 1, :max => 100 %>
        </div>
      </div>
      <div class="row-fluid spacer">
        <%= f.submit "Registrovat", :class => "btn btn-large spacer btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

src/refactofing/app/views/users/recipes.html.erb
<div class="span8 offset2 well">
  <h2>Moje recepty</h2>
  <div class="row-fluid spacer">
    <div class="span5">
      <legend>Napsané recepty</legend>
      <ul class="unstyled">
        <% @recipes.each do |recipe| %>
          <li><%= link_to recipe.name, recipe_path(recipe) %> - <%= l recipe.created_at  %></li>
        <% end %>
      </ul>
      <a class="btn spacer" href="<%= new_recipe_path %> "><i class="icon-pencil"></i> Napsat nový recept</a>
    </div>

    <div class="span6 pull-right">
      <legend>Hodnocené a komentované recepty</legend>
      <ul class="unstyled">
        <% @splitted.each do |splitted| %>
          <li><%= link_to splitted.name, recipe_path(splitted) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

src/refactofing/app/views/users/reset_password.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="span8 offset2 well">
    <b>E-mail:</b>
    <%= text_field_tag :email %>
    <%= submit_tag "Resetovat heslo!" %>
  </div>
<% end %>

src/refactofing/app/views/users/show.html.erb
<div class="span8 offset2 well pagination-centered">
  <h2>Detail uživatele</h2>
  <p>
    <b>Username:</b>
    <%= @user.username %>
  </p>

  <p>
    <b>Email:</b>
    <%= @user.email %>
  </p>

  <p>
    <b>Jméno:</b>
    <%= (@user.first_name ? @user.first_name : "") + " " + (@user.second_name ? @user.second_name : "") %>
  </p>

  <p>
    <b>Typ uživatele (dle oprávnění)</b>
    <%= @user.self_ruleset == RULES_SELF_DEFAULT && @user.others_ruleset == RULES_OTHERS_DEFAULT ? "Běžný uživatel" : "Uživatel s upravenými pravomocemi"%>
  </p>

  <p>
    <b>Aktivní:</b>
    <%= print_bool(:bool => @user.active) %>
  </p>

  <hr />

  <p>
    <b>Poznámka</b>
  </p>
  <p>
    <%= @user.note ? @user.note : "žádná" %>
  </p>

  <hr />

  <div class="spacer"></div>

  <p>
    <% get_action_buttons(@user).each do |button| %>
      <%= button %>
    <% end %>
  </p>
</div>