src/refactofing/config/routes.rb
CookBook::Application.routes.draw do
  get "logs/index"
  get "logs/show"
  get "logs/detail"

  resources :password_resets
  resources :user_sessions
  resources :articles
  resources :ingredience_categories
  resources :recipe_categories
  resources :comments

  resources :users do
    member do
      get :activate
      get :recipes
      get :articles
      get :block
      get :unblock
      put :change_password
    end
    
    collection do
      get "reset_password"
    end
  end

  resources :recipes do
    member do
      get "add_ingredience"
      get "remove_ingredience"
      get "add_category"
      get "remove_category"
      get "add_connected_article"
      get "remove_connected_article"
      get "add_subrecipe"
      get "remove_subrecipe"
    end

    collection do
      get "fridge"
      get "newest"
    end
  end
  
  resources :ingrediences do
    collection do
      get "new_request"
    end
  end

  get "help/index"

  get "home/index"
  get "home/search"
  get "home/success"
  get "home/error"
  get "index/home"

  get "user_sessions/create"
  get "user_sessions/destroy"

  get "marks/create"
  get "marks/index"
  get "marks/destroy"

  match 'login' => 'user_sessions#create', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'my_profile' => 'users#show'
  match 'my_recipes' => 'users#recipes'
  match 'my_articles' => 'users#articles'

  match 'fridge' => 'recipes#fridge'
  match 'filter' => 'recipes#filter'
  match 'search' => 'home#search'
  
  match 'logs' => 'logs#index'

  match 'marks' => 'marks#index'

  root :to => 'home#index'

end

src/refactofing/app/models/ingredience_category.rb
# coding:utf-8

class IngredienceCategory < ActiveRecord::Base
  has_and_belongs_to_many :ingrediences

  belongs_to :user

  attr_accessible :name, :description, :category_type, :user, :user_id

  validates :name,
    :length => { :minimum => 3, :maximum => 255, :message => VALIDATION_ERROR_MESSAGE["ingredience_category"]["name"] }

  validates :description,
    :length => { :minimum => 20, :message => VALIDATION_ERROR_MESSAGE["ingredience_category"]["description"] },
    :allow_blank => true

  validates :category_type,
    :numericality => { :only_integer => true, :greater_than_or_equal_to => 0, :message => VALIDATION_ERROR_MESSAGE["ingredience_category"]["category_type"] }

  validates :user_id,
    :presence => { :message => VALIDATION_ERROR_MESSAGE["ingredience_category"]["user_id"] },
    :numericality => { :only_integer => true, :greater_than => 0, :message => VALIDATION_ERROR_MESSAGE["ingredience_category"]["user_id"] }
  validates :user, :associated => { :message => VALIDATION_ERROR_MESSAGE["ingredience_category"]["user_id"] }
end

src/refactofing/app/controllers/ingredience_categories_controller.rb
# coding:utf-8

class IngredienceCategoriesController < ApplicationController
  before_filter :user_rights_filter

  # GET /ingredience_categories
  def index
    @ingredience_categories = IngredienceCategory.all
  end

  # GET /ingredience_categories/1
  def show
    @ingredience_category = IngredienceCategory.find(params[:id])
  end

  # GET /ingredience_categories/new
  def new
    @ingredience_category = IngredienceCategory.new
  end

  # GET /ingredience_categories/1/edit
  def edit
    @ingredience_category = IngredienceCategory.find(params[:id])
  end

  # POST /ingredience_categories
  def create
    @ingredience_category = IngredienceCategory.new(params[:ingredience_category])
    @ingredience_category.user = current_user

    if @ingredience_category.save
      redirect_to @ingredience_category, notice: 'Ingredience category was successfully created.'
    else
      @errors = @ingredience_category.errors
      render action: "new"
    end
  end

  # PUT /ingredience_categories/1
  def update
    @ingredience_category = IngredienceCategory.find(params[:id])

    if @ingredience_category.update_attributes(params[:ingredience_category])
      redirect_to @ingredience_category, notice: 'Ingredience category was successfully updated.'
    else
      @errors = @ingredience_category.errors
      render action: "edit"
    end
  end

  # DELETE /ingredience_categories/1
  def destroy
    @ingredience_category = IngredienceCategory.find(params[:id])
    @ingredience_category.destroy

    redirect_to ingredience_categories_url
  end
end

src/refactofing/app/helpers/ingredience_categories_helper.rb
module IngredienceCategoriesHelper
end

src/refactofing/app/views/ingredience_categories/_form.html.erb
<script type="text/javascript" src="<%= asset_path "pages/ingredience_categories_form.js" %>"></script>

<%= form_for(@ingredience_category, :html => { :onsubmit => "return Validator.validate({ group: \"ingredience_category_form\", showMessage: false })" }) do |f| %>
  <%= render "layouts/errors" %>

  <label>Název</label>
  <%= f.text_field :name %>
  <label>Popis</label>
  <%= f.text_area :description, :class => "input-block-level", :rows => "6" %>
  <%= f.submit :value => "Vytvořit", :class => "btn" %>
<% end %>

src/refactofing/app/views/ingredience_categories/edit.html.erb
<div class="span8 offset2">
  <div class="well">
    <h2>Editace kategorie</h2>
    <%= render 'form' %>
  </div>
</div>

src/refactofing/app/views/ingredience_categories/index.html.erb
<div class="span8 offset2">
  <div class="well">
    <h2>Kategorie ingrediencí</h2>
    <table class="table table-hower spacer">
      <tr>
        <th>Název</th>
        <th>Popis</th>
        <th>Akce</th>
      </tr>

      <% @ingredience_categories.each do |ingredience_category| %>
        <tr>
          <td><%= ingredience_category.name %></td>
          <td><%= ingredience_category.description %></td>
          <td class="btn-group">
            <%= link_to 'Zobrazit', ingredience_category, :class => "btn" %>
            <%= link_to 'Editovat', edit_ingredience_category_path(ingredience_category), :class => "btn" %>
            <%= link_to 'Smazat', ingredience_category, :class => "btn", method: :delete, data: { confirm: 'Jste si jistý(á)?' } %>
          </td>
        </tr>
      <% end %>
    </table>
    <%= ingredience_categories_filter("new", nil, nil) ? button_to('Nová kategorie', new_ingredience_category_path, :class => "btn", method: :get) : nil %>
  </div>
</div>

src/refactofing/app/views/ingredience_categories/new.html.erb
<div class="span8 offset2">
  <div class="well">
    <h2>Nová kategorie</h2>
    <%= render 'form' %>
  </div>
</div>

src/refactofing/app/views/ingredience_categories/show.html.erb
<div class="span8 offset2">
  <div class="well">
    <h2><%= @ingredience_category.name %></h2>
    <div class="spacer">
      <p>
        <%= simple_format @ingredience_category.description %>
      </p>
      <div class="btn-group">
        <% if ingredience_categories_filter("edit", nil, @ingredience_category) %>
          <%= link_to('Editovat', edit_ingredience_category_path(@ingredience_category), :class => "btn") %>
        <% end %>

        <% if ingredience_categories_filter("destroy", nil, @ingredience_category) %>
          <%= link_to('Smazat', @ingredience_category, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn") %>
        <% end %>
        
        <% if ingredience_categories_filter("index", nil, @ingredience_category) %>
          <%= link_to('Seznam', ingredience_categories_path, :class => "btn") %>
        <% end %>
      </div>
    </div>
  </div>
</div>