src/rails/config/routes.rb
PokusSorcery::Application.routes.draw do
  
  get "help/index"

  get "home/index"
  get "home/search"
  get "home/success"
  get "home/error"
  get "home/plain_message"
  get "index/home"
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"
  get "marks/create"
  get "marks/index"
  get "marks/destroy"
  get "recipes/fridge"
  get "recipes/newest"
  get "recipes/add_subrecipe"
  get "ingrediences/new_request"
  get "ingrediences/plain_list"

  root :to => 'home#index'
  resources :users do
    member do
      get :activate
    end
  end
  
  resources :user_sessions
  resources :recipes
  resources :articles
  resources :ingrediences
  resources :ingredience_categories
  resources :recipe_categories
  resources :comments

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  match 'my_profile' => 'users#show'
  match 'my_recipes' => 'users#recipes'
  match 'my_articles' => 'users#articles'

  match 'recipes/:id/add_subrecipe' => 'recipes#add_subrecipe'
  match 'recipes/:id/remove_subrecipe' => 'recipes#remove_subrecipe'
  match 'recipes/:id/add_connected_article' => 'recipes#add_connected_article'
  match 'recipes/:id/remove_connected_article' => 'recipes#remove_connected_article'
  match 'users/:id/recipes' => 'users#recipes'
  match 'users/:id/articles' => 'users#articles'
  match 'users/:id/block' => 'users#block'
  match 'users/:id/unblock' => 'users#unblock'
  match 'fridge' => 'recipes#fridge'
  match 'filter' => 'recipes#filter'
  match 'search' => 'home#search'

end

src/rails/app/models/ingredience.rb
# coding:utf-8

class Ingredience < ActiveRecord::Base
  belongs_to :user

  has_many :comments
  has_many :ingredienceRecipeConnectors
  has_many :recipes, :through => :ingredienceRecipeConnectors

  has_and_belongs_to_many :ingredienceCategories

  attr_accessible :name, :annotation, :content, :avaliability, :units, :activation_state

  validates :name,
    :length => { :minimum => 3, :maximum => 50, :message => "špatná délka názvu (3-50)" },
    :uniqueness => { :case_sensitive => false, :message => "ingredience s daným názvem již existuje" },
  :if => :name

  validates :annotation,
    :length => { :minimum => 50, :maximum => 255, :message => "špatná délka anotace (50-255)" },
    :allow_blank => true,
  :if => :annotation

  validates :content,
    :length => { :minimum => 100, :message => "špatná délka obsahu (alespoň 100 znaků)" },
    :allow_blank => true,
  :if => :content

  validates :avaliability,
    :numericality => { :only_integer => true, :greater_than_or_equal_to => 1, :less_than_or_equal_to => 1000, :message => "chybná dostupnost (musí být v rozmezí 1-1000)" },
  :if => :avaliability

  validates :activation_state,
    :numericality => { :only_integer => true, :greater_than_or_equal_to => 0, :less_than_or_equal_to => 1, :message => "chybný aktivační status (musí být v rozmezí 0-1)" },
  :if => :activation_state

  #validates :units,
  #:if => :units
end

src/rails/app/controllers/ingrediences_controller.rb
class IngrediencesController < ApplicationController
  before_filter :user_rights_filter

  # GET /ingrediences
  # GET /ingrediences.json
  def index
    @ingrediences_accepted = Ingredience.where(:activation_state => 1).order(:name).all
    @ingrediences_pending = Ingredience.where(:activation_state => 0).order(:name).all
  end

  # GET /ingrediences/1
  def show
    @ingredience = Ingredience.find(params[:id])

    # seznam komentaru pro clanek
    @comments = Comment.where(:comment_type => COMMENT_TYPE['ingrediences'], :ingredience_id => @ingredience.id)

    # entita na pridani noveho komentare
    @comment = Comment.new
    @comment.comment_type = COMMENT_TYPE['ingrediences']
    @comment.user = current_user
    @comment.ingredience = @ingredience
  end

  # GET /ingrediences/new
  def new
    @ingredience = Ingredience.new
  end

  # GET /ingrediences/1/edit
  def edit
    @ingredience = Ingredience.find(params[:id])
  end

  # POST /ingrediences
  def create
    @ingredience = Ingredience.new(params[:ingredience])
    @ingredience.user = current_user

    if @ingredience.save
      redirect_to @ingredience, notice: 'Ingredience was successfully created.'
    else
      @errors = @ingredience.errors
      render action: "new"
    end
  end

  # PUT /ingrediences/1
  def update
    @ingredience = Ingredience.find(params[:id])

    if @ingredience.update_attributes(params[:ingredience])
      redirect_to @ingredience, notice: 'Ingredience was successfully updated.'
    else
      @errors = @ingredience.errors
      render action: "edit"
    end
  end

  # DELETE /ingrediences/1
  def destroy
    @ingredience = Ingredience.find(params[:id])
    @ingredience.destroy

    redirect_to ingrediences_url
  end

  def new_request
    @ingredience = Ingredience.new
    @ingredience.name = params[:name]
    @ingredience.units = params[:units]
    @ingredience.annotation = params[:annotation]
    @ingredience.content = params[:content]
    @ingredience.user = current_user

    if @ingredience.save
      @msg = "true"
    else
      @msg = "false"
    end

    redirect_to "/home/plain_message", notice: @msg
  end

  def plain_list
    @ingrediences = Ingredience.order(:name).all
  end
end

src/rails/app/views/ingrediences/_form.html.erb
<%= form_for(@ingredience) do |f| %>
  <%= render "layouts/errors" %>

  <div class="row-fluid spacer">
    <label><strong>Název</strong></label>
    <%= f.text_field :name, :class => "text4" %>
    <label>Anotace</label>
    <%= f.text_area :annotation, :rows => 5, :class => "input-block-level" %>
    <label>Obsah</label>
    <%= f.text_area :content, :rows => 5, :class => "input-block-level" %>
    <label>Dostupnost</label>
    <%= f.number_field :avaliability, :min => 1, :max => 1000 %>
    <label>Jednotky</label>
    <%= f.text_field :units %>
    <label>
      Schválená
      <%= f.check_box :activation_state %>
    </label>
    <div class="btn-group spacer">
      <%= f.submit 'Nastavit', :class => "btn" %>
      <% if ingrediences_filter("index", nil, @ingredience) %>
        <%= link_to('Seznam', ingrediences_path, :class => "btn") %>
      <% end %>
    </div>
  </div>
<% end %>

src/rails/app/views/ingrediences/edit.html.erb
<div class="span8 offset2">
  <div class="well">
    <h1>Editace ingredience</h1>
    <%= render "form" %>
  </div>
</div>

src/rails/app/views/ingrediences/index.html.erb
<div class="span10 offset1">
  <div class="well">
    <h2>Ingredience - schválené</h2>
    <table class="table table-hower spacer">
      <thead>
        <tr>
          <th>#</th>
          <th>Název</th>
          <th>Autor</th>
          <th>Akce</th>
        </tr>
      </thead>
      <tbody>
        <% @ingrediences_accepted.each do |ingredience| %>
          <tr>
            <td><%= ingredience.id %></td>
            <td><%= ingredience.name %></td>
            <td><%= ingredience.user.username %></td>
            <td>
              <%= ingrediences_filter("show", nil, ingredience) ? link_to('Zobrazit', ingredience, :method => :get, :class => "btn") : nil %>
              <%= ingrediences_filter("edit", nil, ingredience) ? link_to('Editovat', edit_ingredience_path(ingredience), :method => :get, :class => "btn") : nil %>
              <%= ingrediences_filter("destroy", nil, ingredience) ? link_to('Smazat', ingredience, :method => :delete, data: { confirm: 'Jste si jistý(á)?' }, :class => "btn") : nil %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <h2>Ingredience - neschválené</h2>
    <table class="table table-hower spacer">
      <thead>
        <tr>
          <th>#</th>
          <th>Název</th>
          <th>Autor</th>
          <th>Akce</th>
        </tr>
      </thead>
      <tbody>
        <% @ingrediences_pending.each do |ingredience| %>
          <tr>
            <td><%= ingredience.id %></td>
            <td><%= ingredience.name %></td>
            <td><%= ingredience.user.username %></td>
            <td>
              <%= ingrediences_filter("show", nil, ingredience) ? link_to('Zobrazit', ingredience, :method => :get, :class => "btn") : nil %>
              <%= ingrediences_filter("edit", nil, ingredience) ? link_to('Editovat', edit_ingredience_path(ingredience), :method => :get, :class => "btn") : nil %>
              <%= ingrediences_filter("destroy", nil, ingredience) ? link_to('Smazat',ingredience, :method => :delete, data: { confirm: 'Jste si jistý(á)?' }, :class => "btn") : nil %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= ingrediences_filter("new", nil, nil) ? button_to('Nová ingredience', new_ingredience_path, {:class => "btn", :method => :get}) : nil %>
  </div>
</div>

src/rails/app/views/ingrediences/new.html.erb
<div class="span8 offset2">
  <div class="well">
    <h1>Nová ingredience</h1>
    <%= render "form" %>
  </div>
</div>

src/rails/app/views/ingrediences/show.html.erb
<div class="span8 offset2">
  <div class="well">
    <h2><%= @ingredience.name %></h2>
    <div class="row-fluid spacer">
      <div class="span6">
        <label><strong>Autor: </strong><%= link_to @ingredience.user.username, user_path(@ingredience.user) %></label>
        <label><strong>Jednotky: </strong><%= @ingredience.units %></label>
        <label><strong>Dostupnost: </strong><%= @ingredience.avaliability %></label>
      </div>
      <div class="span6">
      </div>
    </div>

    <div class="row-fluid">
      <h4>Popis</h4>
      <p>
        <%= @ingredience.annotation %>
      </p>
      <p>
        <%= @ingredience.content %>
      </p>

      <div class="btn-group">
        <% if ingrediences_filter("edit", nil, @ingredience) %>
          <%= link_to('Editovat', edit_ingredience_path(@ingredience), :class => "btn") %>
        <% end %>

        <% if ingrediences_filter("destroy", nil, @ingredience) %>
          <%= link_to('Smazat', { :controller => 'ingrediences', :action => 'destroy', :id => @ingredience.id}, data: { confirm: 'Jste si jistý(á)?' }, :class => "btn") %>
        <% end %>

        <% if ingrediences_filter("index", nil, @ingredience) %>
          <%= link_to('Seznam', ingrediences_path, :class => "btn") %>
        <% end %>
      </div>
    </div>

    <legend class="spacer"></legend>

    <%= render "comments/list" %>
    <%= render "comments/form" %>
  </div>
</div>